name: magnet
description: An interface for scraping student data for the Academia platform
version: 1.0.0
repository: https://github.com/opencrafts-io/magnet.git

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
  # path: ^1.8.0

dev_dependencies:
  build_runner: ^2.5.4
  freezed: ^3.1.0
  json_serializable: ^6.9.5
  lints: ^5.0.0
  test: ^1.24.0
dependencies:
  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
