name: magnet
description: An interface for scraping student data for the Academia platform
version: 1.0.0
repository: https://github.com/opencrafts-io/magnet.git

environment:
  sdk: ^3.8.1

# Add regular dependencies here.
dependencies:
  freezed: ^3.1.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
